// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Scrinium.Infrastructure.Persistence;

#nullable disable

namespace Scrinium.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ScriniumDbContext))]
    partial class ScriniumDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Scrinium.Core.Domain.Archive", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint");

                    b.Property<string>("ClientMetadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ExtractedMetadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ExtractionWarnings")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("IngestCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IngestQuality")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset?>("IngestStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ProcessingStep")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SheetCount")
                        .HasColumnType("integer");

                    b.Property<int>("SheetsFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("StagingPath")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TraceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("UploadedAt");

                    b.ToTable("archives", (string)null);
                });

            modelBuilder.Entity("Scrinium.Core.Domain.ArchiveSheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArchiveId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasTextLayer")
                        .HasColumnType("boolean");

                    b.Property<string>("HocrObjectKey")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("HocrWords")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<float?>("OcrConfidence")
                        .HasColumnType("real");

                    b.Property<string>("PlainText")
                        .HasColumnType("text");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("RenderStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("SequenceInArchive")
                        .HasColumnType("integer");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveId", "SequenceInArchive")
                        .IsUnique();

                    b.ToTable("archive_sheets", (string)null);
                });

            modelBuilder.Entity("Scrinium.Core.Domain.Bundle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("FinalizeEnqueued")
                        .HasColumnType("boolean");

                    b.Property<string>("IngestQuality")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("ReadyAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SheetsFailedCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SourceArchiveId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("TraceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("SourceArchiveId");

                    b.HasIndex("Status");

                    b.ToTable("bundles", (string)null);
                });

            modelBuilder.Entity("Scrinium.Core.Domain.BundleTag", b =>
                {
                    b.Property<Guid>("BundleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("BundleId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("bundle_tags", (string)null);
                });

            modelBuilder.Entity("Scrinium.Core.Domain.IngestStepLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArchiveId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArchiveSheetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BundleId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TraceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("WorkerType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("TraceId");

                    b.HasIndex("ArchiveId", "StartedAt");

                    b.HasIndex("ArchiveSheetId", "StartedAt");

                    b.HasIndex("BundleId", "StartedAt");

                    b.ToTable("ingest_step_log", (string)null);
                });

            modelBuilder.Entity("Scrinium.Core.Domain.Sheet", b =>
                {
                    b.Property<Guid>("BundleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArchiveSheetId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("BundleId", "ArchiveSheetId");

                    b.HasIndex("ArchiveSheetId");

                    b.HasIndex("BundleId", "SortOrder")
                        .IsUnique();

                    b.ToTable("sheets", (string)null);
                });

            modelBuilder.Entity("Scrinium.Core.Domain.SheetBarcode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArchiveSheetId")
                        .HasColumnType("uuid");

                    b.Property<string>("BoundingBox")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("bounding_box");

                    b.Property<float>("Confidence")
                        .HasColumnType("real");

                    b.Property<string>("Symbology")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveSheetId");

                    b.HasIndex("Value");

                    b.ToTable("sheet_barcodes", (string)null);
                });

            modelBuilder.Entity("Scrinium.Core.Domain.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Scrinium.Core.Domain.ArchiveSheet", b =>
                {
                    b.HasOne("Scrinium.Core.Domain.Archive", "Archive")
                        .WithMany("ArchiveSheets")
                        .HasForeignKey("ArchiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Archive");
                });

            modelBuilder.Entity("Scrinium.Core.Domain.Bundle", b =>
                {
                    b.HasOne("Scrinium.Core.Domain.Archive", "SourceArchive")
                        .WithMany("Bundles")
                        .HasForeignKey("SourceArchiveId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SourceArchive");
                });

            modelBuilder.Entity("Scrinium.Core.Domain.BundleTag", b =>
                {
                    b.HasOne("Scrinium.Core.Domain.Bundle", "Bundle")
                        .WithMany("BundleTags")
                        .HasForeignKey("BundleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scrinium.Core.Domain.Tag", "Tag")
                        .WithMany("BundleTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bundle");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Scrinium.Core.Domain.Sheet", b =>
                {
                    b.HasOne("Scrinium.Core.Domain.ArchiveSheet", "ArchiveSheet")
                        .WithMany("BundleMemberships")
                        .HasForeignKey("ArchiveSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Scrinium.Core.Domain.Bundle", "Bundle")
                        .WithMany("Sheets")
                        .HasForeignKey("BundleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArchiveSheet");

                    b.Navigation("Bundle");
                });

            modelBuilder.Entity("Scrinium.Core.Domain.SheetBarcode", b =>
                {
                    b.HasOne("Scrinium.Core.Domain.ArchiveSheet", "ArchiveSheet")
                        .WithMany("Barcodes")
                        .HasForeignKey("ArchiveSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArchiveSheet");
                });

            modelBuilder.Entity("Scrinium.Core.Domain.Archive", b =>
                {
                    b.Navigation("ArchiveSheets");

                    b.Navigation("Bundles");
                });

            modelBuilder.Entity("Scrinium.Core.Domain.ArchiveSheet", b =>
                {
                    b.Navigation("Barcodes");

                    b.Navigation("BundleMemberships");
                });

            modelBuilder.Entity("Scrinium.Core.Domain.Bundle", b =>
                {
                    b.Navigation("BundleTags");

                    b.Navigation("Sheets");
                });

            modelBuilder.Entity("Scrinium.Core.Domain.Tag", b =>
                {
                    b.Navigation("BundleTags");
                });
#pragma warning restore 612, 618
        }
    }
}
